[book]
authors = ["Johannes Lötzsch"]
language = "en"
multilingual = false
src = "src"
title = "Forms Wizard"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
